# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1921, 1071))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.group_postav = QtWidgets.QGroupBox(self.page)
        self.group_postav.setGeometry(QtCore.QRect(680, 30, 241, 201))
        self.group_postav.setWhatsThis("")
        self.group_postav.setStyleSheet("QGroupBox{\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    border: 0px solid black;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.group_postav.setTitle("")
        self.group_postav.setObjectName("group_postav")
        self.label_4 = QtWidgets.QLabel(self.group_postav)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 151, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.group_postav)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 151, 18))
        self.label_5.setObjectName("label_5")
        self.address = QtWidgets.QLineEdit(self.group_postav)
        self.address.setGeometry(QtCore.QRect(10, 110, 221, 31))
        self.address.setObjectName("address")
        self.provider = QtWidgets.QLineEdit(self.group_postav)
        self.provider.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.provider.setObjectName("provider")
        self.ok = QtWidgets.QPushButton(self.group_postav)
        self.ok.setGeometry(QtCore.QRect(10, 150, 101, 31))
        self.ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(self.group_postav)
        self.cancel.setGeometry(QtCore.QRect(130, 150, 101, 31))
        self.cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel.setObjectName("cancel")
        self.group_postav_change = QtWidgets.QGroupBox(self.page)
        self.group_postav_change.setGeometry(QtCore.QRect(550, 210, 241, 201))
        self.group_postav_change.setWhatsThis("")
        self.group_postav_change.setStyleSheet("QGroupBox{\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    border: 0px solid black;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.group_postav_change.setTitle("")
        self.group_postav_change.setObjectName("group_postav_change")
        self.label_10 = QtWidgets.QLabel(self.group_postav_change)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 151, 18))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.group_postav_change)
        self.label_11.setGeometry(QtCore.QRect(10, 80, 151, 18))
        self.label_11.setObjectName("label_11")
        self.address_change = QtWidgets.QLineEdit(self.group_postav_change)
        self.address_change.setGeometry(QtCore.QRect(10, 110, 221, 31))
        self.address_change.setObjectName("address_change")
        self.provider_change = QtWidgets.QLineEdit(self.group_postav_change)
        self.provider_change.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.provider_change.setObjectName("provider_change")
        self.ok_change = QtWidgets.QPushButton(self.group_postav_change)
        self.ok_change.setGeometry(QtCore.QRect(10, 150, 101, 31))
        self.ok_change.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_change.setObjectName("ok_change")
        self.cancel_change = QtWidgets.QPushButton(self.group_postav_change)
        self.cancel_change.setGeometry(QtCore.QRect(130, 150, 101, 31))
        self.cancel_change.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_change.setObjectName("cancel_change")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(0, -2, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.group_postav_3 = QtWidgets.QGroupBox(self.page)
        self.group_postav_3.setGeometry(QtCore.QRect(1670, 30, 241, 191))
        self.group_postav_3.setStyleSheet("QGroupBox{\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    border: 0px solid black;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox::down-arrow{\n"
"    \n"
"}")
        self.group_postav_3.setTitle("")
        self.group_postav_3.setObjectName("group_postav_3")
        self.label_8 = QtWidgets.QLabel(self.group_postav_3)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 151, 18))
        self.label_8.setObjectName("label_8")
        self.comboBox = QtWidgets.QComboBox(self.group_postav_3)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_9 = QtWidgets.QLabel(self.group_postav_3)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 151, 18))
        self.label_9.setObjectName("label_9")
        self.ok_3 = QtWidgets.QPushButton(self.group_postav_3)
        self.ok_3.setGeometry(QtCore.QRect(10, 150, 101, 31))
        self.ok_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_3.setObjectName("ok_3")
        self.cancel_3 = QtWidgets.QPushButton(self.group_postav_3)
        self.cancel_3.setGeometry(QtCore.QRect(130, 150, 101, 31))
        self.cancel_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_3.setObjectName("cancel_3")
        self.name = QtWidgets.QLineEdit(self.group_postav_3)
        self.name.setGeometry(QtCore.QRect(10, 110, 221, 31))
        self.name.setObjectName("name")
        self.group_postav_change_2 = QtWidgets.QGroupBox(self.page)
        self.group_postav_change_2.setGeometry(QtCore.QRect(550, 715, 241, 201))
        self.group_postav_change_2.setStyleSheet("\n"
"border: 1px solid black;")
        self.group_postav_change_2.setTitle("")
        self.group_postav_change_2.setObjectName("group_postav_change_2")
        self.label_12 = QtWidgets.QLabel(self.group_postav_change_2)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 151, 18))
        self.label_12.setStyleSheet("border: none;")
        self.label_12.setObjectName("label_12")
        self.number_change = QtWidgets.QLineEdit(self.group_postav_change_2)
        self.number_change.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.number_change.setObjectName("number_change")
        self.date_change = QtWidgets.QLineEdit(self.group_postav_change_2)
        self.date_change.setGeometry(QtCore.QRect(10, 110, 201, 31))
        self.date_change.setStyleSheet("\n"
"border: 1px solid black;")
        self.date_change.setObjectName("date_change")
        self.label_13 = QtWidgets.QLabel(self.group_postav_change_2)
        self.label_13.setGeometry(QtCore.QRect(10, 80, 151, 18))
        self.label_13.setStyleSheet("border: none;")
        self.label_13.setObjectName("label_13")
        self.ok_change_2 = QtWidgets.QPushButton(self.group_postav_change_2)
        self.ok_change_2.setGeometry(QtCore.QRect(10, 150, 101, 31))
        self.ok_change_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_change_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ok_change_2.setObjectName("ok_change_2")
        self.cancel_change_2 = QtWidgets.QPushButton(self.group_postav_change_2)
        self.cancel_change_2.setGeometry(QtCore.QRect(130, 150, 101, 31))
        self.cancel_change_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_change_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cancel_change_2.setObjectName("cancel_change_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.group_postav_change_2)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 110, 21, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("border-top-right-radius: 0px;\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableView = QtWidgets.QTableView(self.page)
        self.tableView.setGeometry(QtCore.QRect(0, 30, 531, 501))
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setCascadingSectionResizes(True)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(0, 540, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(550, 30, 121, 171))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    border: 0px solid black;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::checked{\n"
"    \n"
"    background-color: rgb(222, 221, 218);\n"
"}\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.add = QtWidgets.QPushButton(self.groupBox)
        self.add.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add.setObjectName("add")
        self.dele = QtWidgets.QPushButton(self.groupBox)
        self.dele.setGeometry(QtCore.QRect(10, 90, 101, 31))
        self.dele.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dele.setObjectName("dele")
        self.change_btn = QtWidgets.QPushButton(self.groupBox)
        self.change_btn.setGeometry(QtCore.QRect(10, 50, 101, 31))
        self.change_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_btn.setObjectName("change_btn")
        self.other = QtWidgets.QPushButton(self.groupBox)
        self.other.setGeometry(QtCore.QRect(10, 130, 101, 31))
        self.other.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.other.setObjectName("other")
        self.group_postav_2 = QtWidgets.QGroupBox(self.page)
        self.group_postav_2.setGeometry(QtCore.QRect(680, 570, 241, 201))
        self.group_postav_2.setStyleSheet("QGroupBox{\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    border: 0px solid black;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.group_postav_2.setTitle("")
        self.group_postav_2.setObjectName("group_postav_2")
        self.label_6 = QtWidgets.QLabel(self.group_postav_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 151, 18))
        self.label_6.setStyleSheet("border: none;")
        self.label_6.setObjectName("label_6")
        self.number = QtWidgets.QLineEdit(self.group_postav_2)
        self.number.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.number.setObjectName("number")
        self.date = QtWidgets.QLineEdit(self.group_postav_2)
        self.date.setGeometry(QtCore.QRect(10, 110, 201, 31))
        self.date.setObjectName("date")
        self.label_7 = QtWidgets.QLabel(self.group_postav_2)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 151, 18))
        self.label_7.setStyleSheet("border: none;")
        self.label_7.setObjectName("label_7")
        self.ok_2 = QtWidgets.QPushButton(self.group_postav_2)
        self.ok_2.setGeometry(QtCore.QRect(10, 150, 101, 31))
        self.ok_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ok_2.setObjectName("ok_2")
        self.cancel_2 = QtWidgets.QPushButton(self.group_postav_2)
        self.cancel_2.setGeometry(QtCore.QRect(130, 150, 101, 31))
        self.cancel_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cancel_2.setObjectName("cancel_2")
        self.pushButton = QtWidgets.QPushButton(self.group_postav_2)
        self.pushButton.setGeometry(QtCore.QRect(210, 110, 21, 31))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page)
        self.groupBox_3.setGeometry(QtCore.QRect(1540, 30, 121, 131))
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    border: 0px solid black;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::checked{\n"
"    \n"
"    background-color: rgb(222, 221, 218);\n"
"}\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.del_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.del_3.setGeometry(QtCore.QRect(10, 90, 101, 31))
        self.del_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.del_3.setObjectName("del_3")
        self.add_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.add_3.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.add_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_3.setObjectName("add_3")
        self.change_btn_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.change_btn_3.setGeometry(QtCore.QRect(10, 50, 101, 31))
        self.change_btn_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_btn_3.setObjectName("change_btn_3")
        self.calendarWidget_change = QtWidgets.QCalendarWidget(self.page)
        self.calendarWidget_change.setGeometry(QtCore.QRect(760, 850, 184, 179))
        self.calendarWidget_change.setObjectName("calendarWidget_change")
        self.tableView_2 = QtWidgets.QTableView(self.page)
        self.tableView_2.setGeometry(QtCore.QRect(0, 570, 531, 501))
        self.tableView_2.setStyleSheet("")
        self.tableView_2.setObjectName("tableView_2")
        self.tableView_2.horizontalHeader().setCascadingSectionResizes(True)
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(940, 0, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.group_postav_change_3 = QtWidgets.QGroupBox(self.page)
        self.group_postav_change_3.setGeometry(QtCore.QRect(1540, 170, 241, 191))
        self.group_postav_change_3.setStyleSheet("QGroupBox{\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    border: 0px solid black;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox::down-arrow{\n"
"    \n"
"}")
        self.group_postav_change_3.setTitle("")
        self.group_postav_change_3.setObjectName("group_postav_change_3")
        self.label_16 = QtWidgets.QLabel(self.group_postav_change_3)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 151, 18))
        self.label_16.setObjectName("label_16")
        self.comboBox_change = QtWidgets.QComboBox(self.group_postav_change_3)
        self.comboBox_change.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.comboBox_change.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_change.setObjectName("comboBox_change")
        self.comboBox_change.addItem("")
        self.comboBox_change.addItem("")
        self.comboBox_change.addItem("")
        self.comboBox_change.addItem("")
        self.comboBox_change.addItem("")
        self.label_17 = QtWidgets.QLabel(self.group_postav_change_3)
        self.label_17.setGeometry(QtCore.QRect(10, 80, 151, 18))
        self.label_17.setObjectName("label_17")
        self.ok_change_3 = QtWidgets.QPushButton(self.group_postav_change_3)
        self.ok_change_3.setGeometry(QtCore.QRect(10, 150, 101, 31))
        self.ok_change_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_change_3.setObjectName("ok_change_3")
        self.cancel_change_3 = QtWidgets.QPushButton(self.group_postav_change_3)
        self.cancel_change_3.setGeometry(QtCore.QRect(130, 150, 101, 31))
        self.cancel_change_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_change_3.setObjectName("cancel_change_3")
        self.name_change = QtWidgets.QLineEdit(self.group_postav_change_3)
        self.name_change.setGeometry(QtCore.QRect(10, 110, 221, 31))
        self.name_change.setObjectName("name_change")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.page)
        self.calendarWidget.setGeometry(QtCore.QRect(890, 710, 184, 179))
        self.calendarWidget.setStyleSheet("")
        self.calendarWidget.setObjectName("calendarWidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setGeometry(QtCore.QRect(550, 570, 121, 131))
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    border: 0px solid black;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::checked{\n"
"    \n"
"    background-color: rgb(222, 221, 218);\n"
"}\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.del_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.del_2.setGeometry(QtCore.QRect(10, 90, 101, 31))
        self.del_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.del_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.del_2.setObjectName("del_2")
        self.add_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.add_2.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.add_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.add_2.setObjectName("add_2")
        self.change_btn_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.change_btn_2.setGeometry(QtCore.QRect(10, 50, 101, 31))
        self.change_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_btn_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.change_btn_2.setObjectName("change_btn_2")
        self.tableView_3 = QtWidgets.QTableView(self.page)
        self.tableView_3.setGeometry(QtCore.QRect(940, 30, 581, 1041))
        self.tableView_3.setObjectName("tableView_3")
        self.tableView_3.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView_3.raise_()
        self.group_postav.raise_()
        self.group_postav_change.raise_()
        self.label.raise_()
        self.group_postav_3.raise_()
        self.group_postav_change_2.raise_()
        self.tableView.raise_()
        self.label_2.raise_()
        self.groupBox.raise_()
        self.group_postav_2.raise_()
        self.groupBox_3.raise_()
        self.calendarWidget_change.raise_()
        self.tableView_2.raise_()
        self.label_3.raise_()
        self.group_postav_change_3.raise_()
        self.calendarWidget.raise_()
        self.groupBox_2.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableView_4 = QtWidgets.QTableView(self.page_2)
        self.tableView_4.setGeometry(QtCore.QRect(0, 30, 531, 1041))
        self.tableView_4.setObjectName("tableView_4")
        self.tableView_5 = QtWidgets.QTableView(self.page_2)
        self.tableView_5.setGeometry(QtCore.QRect(940, 30, 581, 1041))
        self.tableView_5.setObjectName("tableView_5")
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setGeometry(QtCore.QRect(940, 0, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_4.setGeometry(QtCore.QRect(550, 30, 121, 171))
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    border: 0px solid black;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::checked{\n"
"    \n"
"    background-color: rgb(222, 221, 218);\n"
"}\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.add_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.add_4.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.add_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_4.setObjectName("add_4")
        self.dele_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.dele_2.setGeometry(QtCore.QRect(10, 90, 101, 31))
        self.dele_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dele_2.setObjectName("dele_2")
        self.change_btn_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.change_btn_4.setGeometry(QtCore.QRect(10, 50, 101, 31))
        self.change_btn_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_btn_4.setObjectName("change_btn_4")
        self.other_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.other_2.setGeometry(QtCore.QRect(10, 130, 101, 31))
        self.other_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.other_2.setObjectName("other_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_5.setGeometry(QtCore.QRect(1540, 30, 121, 131))
        self.groupBox_5.setStyleSheet("QGroupBox{\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    border: 0px solid black;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::checked{\n"
"    \n"
"    background-color: rgb(222, 221, 218);\n"
"}\n"
"")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.add_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.add_5.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.add_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_5.setObjectName("add_5")
        self.dele_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.dele_3.setGeometry(QtCore.QRect(10, 90, 101, 31))
        self.dele_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dele_3.setObjectName("dele_3")
        self.change_btn_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.change_btn_5.setGeometry(QtCore.QRect(10, 50, 101, 31))
        self.change_btn_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_btn_5.setObjectName("change_btn_5")
        self.group_postav_4 = QtWidgets.QGroupBox(self.page_2)
        self.group_postav_4.setGeometry(QtCore.QRect(680, 30, 241, 201))
        self.group_postav_4.setWhatsThis("")
        self.group_postav_4.setStyleSheet("QGroupBox{\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    border: 0px solid black;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.group_postav_4.setTitle("")
        self.group_postav_4.setObjectName("group_postav_4")
        self.label_18 = QtWidgets.QLabel(self.group_postav_4)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 151, 18))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.group_postav_4)
        self.label_19.setGeometry(QtCore.QRect(10, 80, 151, 18))
        self.label_19.setObjectName("label_19")
        self.price = QtWidgets.QLineEdit(self.group_postav_4)
        self.price.setGeometry(QtCore.QRect(10, 110, 221, 31))
        self.price.setObjectName("price")
        self.product = QtWidgets.QLineEdit(self.group_postav_4)
        self.product.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.product.setObjectName("product")
        self.ok_4 = QtWidgets.QPushButton(self.group_postav_4)
        self.ok_4.setGeometry(QtCore.QRect(10, 150, 101, 31))
        self.ok_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_4.setObjectName("ok_4")
        self.cancel_4 = QtWidgets.QPushButton(self.group_postav_4)
        self.cancel_4.setGeometry(QtCore.QRect(130, 150, 101, 31))
        self.cancel_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_4.setObjectName("cancel_4")
        self.group_postav_change_4 = QtWidgets.QGroupBox(self.page_2)
        self.group_postav_change_4.setGeometry(QtCore.QRect(550, 210, 241, 201))
        self.group_postav_change_4.setWhatsThis("")
        self.group_postav_change_4.setStyleSheet("QGroupBox{\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    border: 0px solid black;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.group_postav_change_4.setTitle("")
        self.group_postav_change_4.setObjectName("group_postav_change_4")
        self.label_22 = QtWidgets.QLabel(self.group_postav_change_4)
        self.label_22.setGeometry(QtCore.QRect(10, 10, 151, 18))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.group_postav_change_4)
        self.label_23.setGeometry(QtCore.QRect(10, 80, 151, 18))
        self.label_23.setObjectName("label_23")
        self.price_change = QtWidgets.QLineEdit(self.group_postav_change_4)
        self.price_change.setGeometry(QtCore.QRect(10, 110, 221, 31))
        self.price_change.setObjectName("price_change")
        self.product_change = QtWidgets.QLineEdit(self.group_postav_change_4)
        self.product_change.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.product_change.setObjectName("product_change")
        self.ok_6 = QtWidgets.QPushButton(self.group_postav_change_4)
        self.ok_6.setGeometry(QtCore.QRect(10, 150, 101, 31))
        self.ok_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_6.setObjectName("ok_6")
        self.cancel_6 = QtWidgets.QPushButton(self.group_postav_change_4)
        self.cancel_6.setGeometry(QtCore.QRect(130, 150, 101, 31))
        self.cancel_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_6.setObjectName("cancel_6")
        self.group_postav_6 = QtWidgets.QGroupBox(self.page_2)
        self.group_postav_6.setGeometry(QtCore.QRect(1670, 30, 241, 201))
        self.group_postav_6.setWhatsThis("")
        self.group_postav_6.setStyleSheet("QGroupBox{\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    border: 0px solid black;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.group_postav_6.setTitle("")
        self.group_postav_6.setObjectName("group_postav_6")
        self.label_24 = QtWidgets.QLabel(self.group_postav_6)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 151, 18))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.group_postav_6)
        self.label_25.setGeometry(QtCore.QRect(10, 80, 151, 18))
        self.label_25.setObjectName("label_25")
        self.price_2 = QtWidgets.QLineEdit(self.group_postav_6)
        self.price_2.setGeometry(QtCore.QRect(10, 110, 221, 31))
        self.price_2.setObjectName("price_2")
        self.product_2 = QtWidgets.QLineEdit(self.group_postav_6)
        self.product_2.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.product_2.setObjectName("product_2")
        self.ok_7 = QtWidgets.QPushButton(self.group_postav_6)
        self.ok_7.setGeometry(QtCore.QRect(10, 150, 101, 31))
        self.ok_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_7.setObjectName("ok_7")
        self.cancel_7 = QtWidgets.QPushButton(self.group_postav_6)
        self.cancel_7.setGeometry(QtCore.QRect(130, 150, 101, 31))
        self.cancel_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_7.setObjectName("cancel_7")
        self.group_postav_change_5 = QtWidgets.QGroupBox(self.page_2)
        self.group_postav_change_5.setGeometry(QtCore.QRect(1540, 170, 241, 201))
        self.group_postav_change_5.setWhatsThis("")
        self.group_postav_change_5.setStyleSheet("QGroupBox{\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    border: 0px solid black;\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.group_postav_change_5.setTitle("")
        self.group_postav_change_5.setObjectName("group_postav_change_5")
        self.label_26 = QtWidgets.QLabel(self.group_postav_change_5)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 151, 18))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.group_postav_change_5)
        self.label_27.setGeometry(QtCore.QRect(10, 80, 151, 18))
        self.label_27.setObjectName("label_27")
        self.price_3 = QtWidgets.QLineEdit(self.group_postav_change_5)
        self.price_3.setGeometry(QtCore.QRect(10, 110, 221, 31))
        self.price_3.setObjectName("price_3")
        self.product_3 = QtWidgets.QLineEdit(self.group_postav_change_5)
        self.product_3.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.product_3.setObjectName("product_3")
        self.ok_8 = QtWidgets.QPushButton(self.group_postav_change_5)
        self.ok_8.setGeometry(QtCore.QRect(10, 150, 101, 31))
        self.ok_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_8.setObjectName("ok_8")
        self.cancel_8 = QtWidgets.QPushButton(self.group_postav_change_5)
        self.cancel_8.setGeometry(QtCore.QRect(130, 150, 101, 31))
        self.cancel_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_8.setObjectName("cancel_8")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Название поставщика"))
        self.label_5.setText(_translate("MainWindow", "Адрес"))
        self.ok.setText(_translate("MainWindow", "ОК"))
        self.cancel.setText(_translate("MainWindow", "Отмена"))
        self.label_10.setText(_translate("MainWindow", "Название поставщика"))
        self.label_11.setText(_translate("MainWindow", "Адрес"))
        self.ok_change.setText(_translate("MainWindow", "ОК"))
        self.cancel_change.setText(_translate("MainWindow", "Отмена"))
        self.label.setText(_translate("MainWindow", "Поставщики"))
        self.label_8.setText(_translate("MainWindow", "Название товара"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Кефир"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Молоко"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Свинина"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Сметана"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Тушёнка"))
        self.label_9.setText(_translate("MainWindow", "Количество"))
        self.ok_3.setText(_translate("MainWindow", "ОК"))
        self.cancel_3.setText(_translate("MainWindow", "Отмена"))
        self.label_12.setText(_translate("MainWindow", "Номер накладной"))
        self.label_13.setText(_translate("MainWindow", "Дата"))
        self.ok_change_2.setText(_translate("MainWindow", "ОК"))
        self.cancel_change_2.setText(_translate("MainWindow", "Отмена"))
        self.pushButton_2.setText(_translate("MainWindow", "⯆"))
        self.label_2.setText(_translate("MainWindow", "Накладные"))
        self.add.setText(_translate("MainWindow", "Добавить"))
        self.dele.setText(_translate("MainWindow", "Удалить"))
        self.change_btn.setText(_translate("MainWindow", "Изменить"))
        self.other.setText(_translate("MainWindow", "Другое"))
        self.label_6.setText(_translate("MainWindow", "Номер накладной"))
        self.label_7.setText(_translate("MainWindow", "Дата"))
        self.ok_2.setText(_translate("MainWindow", "ОК"))
        self.cancel_2.setText(_translate("MainWindow", "Отмена"))
        self.pushButton.setText(_translate("MainWindow", "⯆"))
        self.del_3.setText(_translate("MainWindow", "Удалить"))
        self.add_3.setText(_translate("MainWindow", "Добавить"))
        self.change_btn_3.setText(_translate("MainWindow", "Изменить"))
        self.label_3.setText(_translate("MainWindow", "Товары в накладных"))
        self.label_16.setText(_translate("MainWindow", "Название товара"))
        self.comboBox_change.setItemText(0, _translate("MainWindow", "Кефир"))
        self.comboBox_change.setItemText(1, _translate("MainWindow", "Молоко"))
        self.comboBox_change.setItemText(2, _translate("MainWindow", "Свинина"))
        self.comboBox_change.setItemText(3, _translate("MainWindow", "Сметана"))
        self.comboBox_change.setItemText(4, _translate("MainWindow", "Тушёнка"))
        self.label_17.setText(_translate("MainWindow", "Количество"))
        self.ok_change_3.setText(_translate("MainWindow", "ОК"))
        self.cancel_change_3.setText(_translate("MainWindow", "Отмена"))
        self.del_2.setText(_translate("MainWindow", "Удалить"))
        self.add_2.setText(_translate("MainWindow", "Добавить"))
        self.change_btn_2.setText(_translate("MainWindow", "Изменить"))
        self.label_14.setText(_translate("MainWindow", "Накладные"))
        self.label_15.setText(_translate("MainWindow", "Товары"))
        self.add_4.setText(_translate("MainWindow", "Добавить"))
        self.dele_2.setText(_translate("MainWindow", "Удалить"))
        self.change_btn_4.setText(_translate("MainWindow", "Изменить"))
        self.other_2.setText(_translate("MainWindow", "Другое"))
        self.add_5.setText(_translate("MainWindow", "Добавить"))
        self.dele_3.setText(_translate("MainWindow", "Удалить"))
        self.change_btn_5.setText(_translate("MainWindow", "Изменить"))
        self.label_18.setText(_translate("MainWindow", "Товар"))
        self.label_19.setText(_translate("MainWindow", "Цена"))
        self.ok_4.setText(_translate("MainWindow", "ОК"))
        self.cancel_4.setText(_translate("MainWindow", "Отмена"))
        self.label_22.setText(_translate("MainWindow", "Товар"))
        self.label_23.setText(_translate("MainWindow", "Цена"))
        self.ok_6.setText(_translate("MainWindow", "ОК"))
        self.cancel_6.setText(_translate("MainWindow", "Отмена"))
        self.label_24.setText(_translate("MainWindow", "?"))
        self.label_25.setText(_translate("MainWindow", "?"))
        self.ok_7.setText(_translate("MainWindow", "ОК"))
        self.cancel_7.setText(_translate("MainWindow", "Отмена"))
        self.label_26.setText(_translate("MainWindow", "?"))
        self.label_27.setText(_translate("MainWindow", "?"))
        self.ok_8.setText(_translate("MainWindow", "ОК"))
        self.cancel_8.setText(_translate("MainWindow", "Отмена"))
